package Capa_presentacion;

import Capa_negocio.Dato_articulo;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;

public class Formulario extends javax.swing.JFrame {

    public Formulario() {
        initComponents();
        this.setSize(640,315);
        ListarArticulos();
        JBtGrabar.setEnabled(false);
    }
    
    public void ListarArticulos(){
        DefaultTableModel tabla=new DefaultTableModel();
        Dato_articulo objart=new Dato_articulo();
        ArrayList<Dato_articulo> lista2= new ArrayList();
        lista2=objart.ListaArticulos();
        tabla.addColumn("Codigo");
        tabla.addColumn("Nombre");
        tabla.addColumn("Unidad");
        tabla.addColumn("Precio");
        tabla.addColumn("Stock");
        tabla.addColumn("Marca");
        tabla.setRowCount (lista2.size());
        int i = 0;
        for(Dato_articulo x:lista2){
            tabla.setValueAt(x.getArt_cod(),i,0);
            tabla.setValueAt(x.getArt_nom(),i,1);
            tabla.setValueAt(x.getArt_uni(),i,2);
            tabla.setValueAt(x.getArt_pre(),i,3);
            tabla.setValueAt(x.getArt_stk(),i,4);
            tabla.setValueAt(x.getArt_marca(),i,5);
            i++;
        }
        this.jTable2.setModel(tabla);
    }
    
    public void LimpiarCajasTexto(){
        this.JtfCodigo.setText("");
        this.JtfNombre.setText("");
        this.JtfUdeMedida.setText("");
        this.JtfPrecio.setText("");
        this.JtfCantidad.setText("");
        this.JtfMarca.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JtfCodigo = new javax.swing.JTextField();
        JtfNombre = new javax.swing.JTextField();
        JtfUdeMedida = new javax.swing.JTextField();
        JtfPrecio = new javax.swing.JTextField();
        JtfCantidad = new javax.swing.JTextField();
        JtfMarca = new javax.swing.JTextField();
        Nuevo = new javax.swing.JButton();
        JBtGrabar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Salir = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Codigo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 44, -1, -1));

        jLabel3.setText("Unidad de medida:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 78, -1, -1));

        jLabel4.setText("Precio:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 108, -1, -1));

        jLabel5.setText("Cantidad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 138, -1, -1));

        jLabel6.setText("Marca:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 168, -1, -1));

        JtfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(JtfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 6, 100, -1));

        JtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfNombreActionPerformed(evt);
            }
        });
        getContentPane().add(JtfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 40, 100, -1));

        JtfUdeMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfUdeMedidaActionPerformed(evt);
            }
        });
        getContentPane().add(JtfUdeMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 74, 100, -1));
        getContentPane().add(JtfPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 104, 100, -1));
        getContentPane().add(JtfCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 134, 100, -1));

        JtfMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(JtfMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 164, 100, -1));

        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        getContentPane().add(Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 206, -1, -1));

        JBtGrabar.setText("Grabar");
        JBtGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtGrabarActionPerformed(evt);
            }
        });
        getContentPane().add(JBtGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 206, -1, -1));

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        getContentPane().add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 206, -1, -1));

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 206, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 392, 182));

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 244, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        LimpiarCajasTexto();
        JBtGrabar.setEnabled(true);
    }//GEN-LAST:event_NuevoActionPerformed

    private void JBtGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtGrabarActionPerformed
        Dato_articulo objart=new Dato_articulo();
        objart.setArt_cod(this.JtfCodigo.getText());
        objart.setArt_nom(this.JtfNombre.getText());
        objart.setArt_uni(this.JtfUdeMedida.getText());
        objart.setArt_pre(Double.parseDouble(this.JtfPrecio.getText()));
        objart.setArt_stk(Integer.parseInt(this.JtfCodigo.getText()));
        objart.setArt_marca(this.JtfMarca.getText());
        JOptionPane.showMessageDialog(null,objart.GrabarArticulo());
        ListarArticulos();
    }//GEN-LAST:event_JBtGrabarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        Dato_articulo objart= new Dato_articulo();
        objart.setArt_cod(this.JtfCodigo.getText());
        objart.setArt_nom(this.JtfNombre.getText());
        objart.setArt_uni(this.JtfUdeMedida.getText());
        objart.setArt_pre(Double.parseDouble(this.JtfPrecio.getText()));
        objart.setArt_stk(Integer.parseInt(this.JtfCantidad.getText()));
        objart.setArt_marca(this.JtfMarca.getText());
        JOptionPane.showMessageDialog(null, objart.EditarArticulo());
        ListarArticulos();
    }//GEN-LAST:event_ModificarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        int Res=JOptionPane.showConfirmDialog(null,"Esta seguro de Eliminar el articulo"+this.JtfCodigo.getText());
        if(Res==0){
            Dato_articulo objart=new Dato_articulo();
            objart.setArt_cod(this.JtfCodigo.getText());
            JOptionPane.showMessageDialog(null,objart.EliminarArticulo());
            ListarArticulos();
            JOptionPane.showMessageDialog(null,"Articulo eliminado");
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        int r=JOptionPane.showConfirmDialog(null,"Esta seguro?");
        if(r==0){
        System.exit(0);
        }
    }//GEN-LAST:event_SalirActionPerformed

    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MousePressed
        int rec=this.jTable2.getSelectedRow();
        this.JtfCodigo.setText(jTable2.getValueAt(rec, 0).toString());
        this.JtfNombre.setText(jTable2.getValueAt(rec, 1).toString());
        this.JtfUdeMedida.setText(jTable2.getValueAt(rec, 2).toString());
        this.JtfPrecio.setText(jTable2.getValueAt(rec, 3).toString());
        this.JtfCantidad.setText(jTable2.getValueAt(rec, 4).toString());
        this.JtfMarca.setText(jTable2.getValueAt(rec, 5).toString());
    }//GEN-LAST:event_jTable2MousePressed

    private void JtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfNombreActionPerformed

    private void JtfUdeMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfUdeMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfUdeMedidaActionPerformed

    private void JtfMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfMarcaActionPerformed

    private void JtfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton JBtGrabar;
    private javax.swing.JTextField JtfCantidad;
    private javax.swing.JTextField JtfCodigo;
    private javax.swing.JTextField JtfMarca;
    private javax.swing.JTextField JtfNombre;
    private javax.swing.JTextField JtfPrecio;
    private javax.swing.JTextField JtfUdeMedida;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton Nuevo;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
